version: "3"
services:
  5-word-research:
    image: jupyter/datascience-notebook:33add21fab64
    ports:
      - "10000:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${PWD}:/home/jovyan/work
    container_name: 5-word-research
